# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.cache/wt [current_project]
set_property parent.project_path /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/timescale.v
set_property file_type "Verilog Header" [get_files /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/timescale.v]
set_property is_global_include true [get_files /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/timescale.v]
read_verilog -library xil_defaultlib {
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/wb_conmax/wb_conmax_defines.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/wb_conmax/wb_conmax_pri_dec.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/async_fifo.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_defines.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_rfram_generic.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_spram_64x14.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_spram_512x20.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_spram_64x24.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_spram_64x22.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_gmultp2_32x32.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_spram_2048x32_bw.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_mem2reg.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_reg2mem.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/usbf/usbf_defines.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/usbf/usbf_crc5.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/usbf/usbf_crc16.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/wb_conmax/wb_conmax_arb.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/wb_conmax/wb_conmax_pri_enc.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/FifoBuffer.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/mgt/rocketio_wrapper_tile_gt.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_sb_fifo.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_ctrl.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_immu_tlb.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_cfgr.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_dc_fsm.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_ic_tag.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_operandmuxes.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_mult_mac.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_ic_fsm.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_lsu.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_alu.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_genpc.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_dc_ram.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_freeze.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_wbmux.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_if.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_ic_ram.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_sprs.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_dc_tag.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_rf.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_dpram_256x32.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_except.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_dmmu_tlb.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/usbf/usbf_ep_rf.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/usbf/usbf_pa.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/usbf/usbf_pe.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/usbf/usbf_pd.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/usbf/usbf_idma.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/usbf/usbf_utmi_ls.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/wb_conmax/wb_conmax_msel.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/rtlRam.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/mgt/rocketio_wrapper_tile_gt_usrclk_source.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/mgt/rocketio_wrapper_tile.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/mgt/rocketio_wrapper_tile_gt_frame_gen.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/mgt/rocketio_wrapper_tile_gt_frame_check.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_du.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_tt.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_ic_top.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_dc_top.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_dmmu_top.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_immu_top.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_pic.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_pm.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_iwb_biu.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_wb_biu.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_sb.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_qmem_top.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_cpu.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/usbf/usbf_utmi_if.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/usbf/usbf_rf.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/usbf/usbf_wb.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/usbf/usbf_mem_arb.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/usbf/usbf_pl.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/wb_conmax/wb_conmax_rf.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/wb_conmax/wb_conmax_master_if.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/wb_conmax/wb_conmax_slave_if.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/fftTop.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/mgtTop.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/clock_generator.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/or1200/or1200_top.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/usbf/usbf_top.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/wb_conmax/wb_conmax_top.v
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/top.v
}
read_vhdl -library bftLib {
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/bftLib/core_transform.vhdl
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/bftLib/bft_package.vhdl
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/bftLib/round_3.vhdl
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/bftLib/round_2.vhdl
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/bftLib/round_4.vhdl
  /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/bftLib/round_1.vhdl
}
read_vhdl -library xil_defaultlib /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/sources_1/imports/Sources/bft.vhdl
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/constrs_2/imports/kintex7/top_full.xdc
set_property used_in_implementation false [get_files /home/hamada/git/Autoware/fpga/proj/autoware_reconfacc/autoware_reconfacc.srcs/constrs_2/imports/kintex7/top_full.xdc]


synth_design -top top -part xc7k70tfbg676-2


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
