# Time-stamp: <2017-01-02 23:29:59 hamada>
#
# Copyright (c) 2017 Tsuyoshi Hamada. All Rights Reserved.
#

all:
	vivado -log top.vds -m64 -product Vivado -mode batch -messageDb vivado.pb -notrace -source top.tcl


clean:
	rm -rf .Xil .vivado.* .Vivado* runme.log top.vds *.pb *.rpt *.jou top.dcp



