# Time-stamp: <2017-01-02 23:02:35 hamada>
#
# Copyright (c) 2017 Tsuyoshi Hamada. All Rights Reserved.
#
# -------
# top.vdi
# top.tcl

all:
	vivado -log top.vdi -applog -m64 -product Vivado -messageDb vivado.pb -mode batch -source top.tcl -notrace


clean:
	rm -rf *.pb *.rpt *.jou *.rpx *.dcp *.vdi

