# Time-stamp: <2017-01-02 23:42:24 hamada>
#
# Copyrignt(c) 2017, Tsuyoshi Hamada. All rights reserved.
#


all: synth impl


synth:
	make -C xilinx-xcu035-fbva676-3-e.runs/synth/

impl: 
	make -C xilinx-xcu035-fbva676-3-e.runs/impl/



clean:
	make -C xilinx-xcu035-fbva676-3-e.runs/synth/ clean
	make -C xilinx-xcu035-fbva676-3-e.runs/impl/ clean

