# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xcku035-fbva676-3-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/hamada/git/Autoware/fpga/modules/logarithmic/xilinx/xilinx.cache/wt [current_project]
set_property parent.project_path /home/hamada/git/Autoware/fpga/modules/logarithmic/xilinx/xilinx.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/hamada/git/Autoware/fpga/modules/logarithmic/xilinx/xilinx.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/hamada/git/Autoware/fpga/modules/logarithmic/logarithmic.vhd
  /home/hamada/git/Autoware/fpga/modules/logarithmic/top.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top top -part xcku035-fbva676-3-e


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
