# 
# Synthesis run script generated by Vivado
# 

set_param project.hsv.suppressChildGraphs 0
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xcku035-fbva676-3-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/hamada/git/Autoware/fpga/GPU_custom/netlist/xilinx-xcu035-fbva676-3-e/xilinx-xcu035-fbva676-3-e.cache/wt [current_project]
set_property parent.project_path /home/hamada/git/Autoware/fpga/GPU_custom/netlist/xilinx-xcu035-fbva676-3-e/xilinx-xcu035-fbva676-3-e.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/hamada/git/Autoware/fpga/GPU_custom/netlist/xilinx-xcu035-fbva676-3-e/xilinx-xcu035-fbva676-3-e.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/hamada/git/Autoware/fpga/GPU_custom/vhdl/gpu_x0.vhd
  /home/hamada/git/Autoware/fpga/GPU_custom/vhdl/gpu_fmul_32ns_32ndEe.vhd
  /home/hamada/git/Autoware/fpga/GPU_custom/vhdl/gpu_control_s_axi.vhd
  /home/hamada/git/Autoware/fpga/GPU_custom/vhdl/gpu_fcmp_32ns_32nfYi.vhd
  /home/hamada/git/Autoware/fpga/GPU_custom/vhdl/gpu_fdiv_32ns_32neOg.vhd
  /home/hamada/git/Autoware/fpga/GPU_custom/vhdl/gpu_fadd_32ns_32nbkb.vhd
  /home/hamada/git/Autoware/fpga/GPU_custom/vhdl/gpu_fsub_32ns_32ncud.vhd
  /home/hamada/git/Autoware/fpga/GPU_custom/vhdl/gpu_gmem_m_axi.vhd
  /home/hamada/git/Autoware/fpga/GPU_custom/vhdl/gpu.vhd
}
read_ip -quiet /home/hamada/git/Autoware/fpga/GPU_custom/netlist/xilinx-xcu035-fbva676-3-e/xilinx-xcu035-fbva676-3-e.srcs/sources_1/ip/gpu_ap_fadd_2_full_dsp_32/gpu_ap_fadd_2_full_dsp_32.xci
set_property is_locked true [get_files /home/hamada/git/Autoware/fpga/GPU_custom/netlist/xilinx-xcu035-fbva676-3-e/xilinx-xcu035-fbva676-3-e.srcs/sources_1/ip/gpu_ap_fadd_2_full_dsp_32/gpu_ap_fadd_2_full_dsp_32.xci]

read_ip -quiet /home/hamada/git/Autoware/fpga/GPU_custom/netlist/xilinx-xcu035-fbva676-3-e/xilinx-xcu035-fbva676-3-e.srcs/sources_1/ip/gpu_ap_fcmp_0_no_dsp_32/gpu_ap_fcmp_0_no_dsp_32.xci
set_property is_locked true [get_files /home/hamada/git/Autoware/fpga/GPU_custom/netlist/xilinx-xcu035-fbva676-3-e/xilinx-xcu035-fbva676-3-e.srcs/sources_1/ip/gpu_ap_fcmp_0_no_dsp_32/gpu_ap_fcmp_0_no_dsp_32.xci]

read_ip -quiet /home/hamada/git/Autoware/fpga/GPU_custom/netlist/xilinx-xcu035-fbva676-3-e/xilinx-xcu035-fbva676-3-e.srcs/sources_1/ip/gpu_ap_fdiv_7_no_dsp_32/gpu_ap_fdiv_7_no_dsp_32.xci
set_property is_locked true [get_files /home/hamada/git/Autoware/fpga/GPU_custom/netlist/xilinx-xcu035-fbva676-3-e/xilinx-xcu035-fbva676-3-e.srcs/sources_1/ip/gpu_ap_fdiv_7_no_dsp_32/gpu_ap_fdiv_7_no_dsp_32.xci]

read_ip -quiet /home/hamada/git/Autoware/fpga/GPU_custom/netlist/xilinx-xcu035-fbva676-3-e/xilinx-xcu035-fbva676-3-e.srcs/sources_1/ip/gpu_ap_fmul_1_max_dsp_32/gpu_ap_fmul_1_max_dsp_32.xci
set_property is_locked true [get_files /home/hamada/git/Autoware/fpga/GPU_custom/netlist/xilinx-xcu035-fbva676-3-e/xilinx-xcu035-fbva676-3-e.srcs/sources_1/ip/gpu_ap_fmul_1_max_dsp_32/gpu_ap_fmul_1_max_dsp_32.xci]

read_ip -quiet /home/hamada/git/Autoware/fpga/GPU_custom/netlist/xilinx-xcu035-fbva676-3-e/xilinx-xcu035-fbva676-3-e.srcs/sources_1/ip/gpu_ap_fsub_2_full_dsp_32/gpu_ap_fsub_2_full_dsp_32.xci
set_property is_locked true [get_files /home/hamada/git/Autoware/fpga/GPU_custom/netlist/xilinx-xcu035-fbva676-3-e/xilinx-xcu035-fbva676-3-e.srcs/sources_1/ip/gpu_ap_fsub_2_full_dsp_32/gpu_ap_fsub_2_full_dsp_32.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top gpu -part xcku035-fbva676-3-e


write_checkpoint -force -noxdef gpu.dcp

catch { report_utilization -file gpu_utilization_synth.rpt -pb gpu_utilization_synth.pb }
