// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xgpu.h"

extern XGpu_Config XGpu_ConfigTable[];

XGpu_Config *XGpu_LookupConfig(u16 DeviceId) {
	XGpu_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XGPU_NUM_INSTANCES; Index++) {
		if (XGpu_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XGpu_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XGpu_Initialize(XGpu *InstancePtr, u16 DeviceId) {
	XGpu_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XGpu_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XGpu_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

