// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XGPU_H
#define XGPU_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xgpu_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_BaseAddress;
} XGpu_Config;
#endif

typedef struct {
    u32 Control_BaseAddress;
    u32 IsReady;
} XGpu;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XGpu_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XGpu_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XGpu_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XGpu_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XGpu_Initialize(XGpu *InstancePtr, u16 DeviceId);
XGpu_Config* XGpu_LookupConfig(u16 DeviceId);
int XGpu_CfgInitialize(XGpu *InstancePtr, XGpu_Config *ConfigPtr);
#else
int XGpu_Initialize(XGpu *InstancePtr, const char* InstanceName);
int XGpu_Release(XGpu *InstancePtr);
#endif

void XGpu_Start(XGpu *InstancePtr);
u32 XGpu_IsDone(XGpu *InstancePtr);
u32 XGpu_IsIdle(XGpu *InstancePtr);
u32 XGpu_IsReady(XGpu *InstancePtr);
void XGpu_EnableAutoRestart(XGpu *InstancePtr);
void XGpu_DisableAutoRestart(XGpu *InstancePtr);

void XGpu_Set_group_id_x(XGpu *InstancePtr, u32 Data);
u32 XGpu_Get_group_id_x(XGpu *InstancePtr);
void XGpu_Set_group_id_y(XGpu *InstancePtr, u32 Data);
u32 XGpu_Get_group_id_y(XGpu *InstancePtr);
void XGpu_Set_group_id_z(XGpu *InstancePtr, u32 Data);
u32 XGpu_Get_group_id_z(XGpu *InstancePtr);
void XGpu_Set_global_offset_x(XGpu *InstancePtr, u32 Data);
u32 XGpu_Get_global_offset_x(XGpu *InstancePtr);
void XGpu_Set_global_offset_y(XGpu *InstancePtr, u32 Data);
u32 XGpu_Get_global_offset_y(XGpu *InstancePtr);
void XGpu_Set_global_offset_z(XGpu *InstancePtr, u32 Data);
u32 XGpu_Get_global_offset_z(XGpu *InstancePtr);
void XGpu_Set_x(XGpu *InstancePtr, u32 Data);
u32 XGpu_Get_x(XGpu *InstancePtr);
void XGpu_Set_y(XGpu *InstancePtr, u32 Data);
u32 XGpu_Get_y(XGpu *InstancePtr);
void XGpu_Set_z(XGpu *InstancePtr, u32 Data);
u32 XGpu_Get_z(XGpu *InstancePtr);

void XGpu_InterruptGlobalEnable(XGpu *InstancePtr);
void XGpu_InterruptGlobalDisable(XGpu *InstancePtr);
void XGpu_InterruptEnable(XGpu *InstancePtr, u32 Mask);
void XGpu_InterruptDisable(XGpu *InstancePtr, u32 Mask);
void XGpu_InterruptClear(XGpu *InstancePtr, u32 Mask);
u32 XGpu_InterruptGetEnabled(XGpu *InstancePtr);
u32 XGpu_InterruptGetStatus(XGpu *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
